info:
  contact: {}
paths:
  /account/login:
    post:
      description: 根据手机号和密码登录
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 密码
        in: query
        name: passWord
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 登录
      tags:
      - 用户
  /account/logout:
    post:
      description: 退出登录
      parameters:
      - description: 用户token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 登出
      tags:
      - 用户
  /contact/findAllContact:
    get:
      description: 查找全部好友
      parameters:
      - description: 当前用户token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 查找全部好友
      tags:
      - 用户关系
  /contact/findContact:
    get:
      description: 查找用户关系
      parameters:
      - description: 当前用户token
        in: header
        name: token
        required: true
        type: string
      - description: 用户ID
        in: query
        name: targetID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 查找用户关系
      tags:
      - 用户关系
  /contact/setContact:
    post:
      description: 设置用户关系
      parameters:
      - description: 当前用户token
        in: header
        name: token
        required: true
        type: string
      - description: 用户ID
        in: query
        name: targetID
        required: true
        type: string
      - description: 用户关系
        in: query
        name: type
        required: true
        type: string
      - description: 备注信息
        in: query
        name: remarks
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 设置用户关系
      tags:
      - 用户关系
  /index:
    get:
      consumes:
      - application/json
      description: 获取配置index信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 获取配置index
      tags:
      - 首页
  /user/deleteUser:
    post:
      description: 删除用户
      parameters:
      - description: 用户token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 删除用户
      tags:
      - 用户
  /user/findUser:
    get:
      description: 查找用户
      parameters:
      - description: 用户ID
        in: query
        name: identify
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 查找用户
      tags:
      - 用户
  /user/findUserList:
    get:
      consumes:
      - application/json
      description: 获取用户列表信息
      parameters:
      - description: 需要查询的用户id字符串(例如xxx,xxx)
        in: query
        name: userIds
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 获取用户列表
      tags:
      - 用户
  /user/registed:
    post:
      description: 创建用户
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 密码
        in: query
        name: passWord
        required: true
        type: string
      - description: 确认密码
        in: query
        name: rePassWord
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 创建用户
      tags:
      - 用户
  /user/updateUser:
    post:
      description: 修改用户
      parameters:
      - description: 用户token
        in: header
        name: token
        required: true
        type: string
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 密码
        in: query
        name: passWord
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: 修改用户
      tags:
      - 用户
swagger: "2.0"
